//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "AmapSearchFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface AmapSearchFluttifyPlugin (SubHandler5)
- (NSDictionary<NSString*, Handler>*) getSubHandler5;
@end

NS_ASSUME_NONNULL_END
