// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:amap_search_fluttify/src/android/android.export.g.dart';
import 'package:amap_search_fluttify/src/ios/ios.export.g.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
Future<bool> isKindOfcom_amap_api_services_traffic_TrafficStatusInfo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_traffic_TrafficStatusInfo', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_traffic_TrafficStatusResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_traffic_TrafficStatusResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_traffic_TrafficSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_traffic_TrafficSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_traffic_TrafficStatusEvaluation(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_traffic_TrafficStatusEvaluation', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_busline_BusLineItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_busline_BusLineItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_busline_BusStationResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_busline_BusStationResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_busline_BusStationSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_busline_BusStationSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_busline_BusLineSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_busline_BusLineSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_busline_BusLineQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_busline_BusLineQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_busline_BusLineResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_busline_BusLineResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_busline_BusStationItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_busline_BusStationItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_busline_BusStationQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_busline_BusStationQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_core_AMapException(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_core_AMapException', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_core_ServiceSettings(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_core_ServiceSettings', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_core_SearchUtils(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_core_SearchUtils', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_core_LatLonSharePoint(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_core_LatLonSharePoint', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_core_LatLonPoint(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_core_LatLonPoint', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_core_PoiItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_core_PoiItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_core_SuggestionCity(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_core_SuggestionCity', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_poisearch_Photo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_poisearch_Photo', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_poisearch_SubPoiItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_poisearch_SubPoiItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_poisearch_PoiItemExtension(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_poisearch_PoiItemExtension', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_poisearch_PoiSearch_SearchBound(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_poisearch_PoiSearch_SearchBound', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_poisearch_PoiResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_poisearch_PoiResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_poisearch_PoiSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_poisearch_PoiSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_poisearch_PoiSearch_Query(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_poisearch_PoiSearch_Query', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_poisearch_IndoorData(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_poisearch_IndoorData', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_Railway(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_Railway', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_BusPath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_BusPath', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DriveRoutePlanResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DriveRoutePlanResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteSearch_TruckRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteSearch_TruckRouteQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_TMC(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_TMC', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteBusWalkItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteBusWalkItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_BusStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_BusStep', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_TaxiItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_TaxiItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_BusRouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_BusRouteResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RoutePlanResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RoutePlanResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RailwaySpace(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RailwaySpace', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_TruckRouteRestult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_TruckRouteRestult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteSearch_RideRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteSearch_RideRouteQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteSearch_DriveRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteSearch_DriveRouteQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteRailwayItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteRailwayItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_WalkStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_WalkStep', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RailwayStationItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RailwayStationItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RideRouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RideRouteResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteSearch_FromAndTo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteSearch_FromAndTo', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RidePath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RidePath', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteSearch_BusRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteSearch_BusRouteQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RideStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RideStep', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteSearchCity(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteSearchCity', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DistanceResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DistanceResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteSearch_WalkRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteSearch_WalkRouteQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_District(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_District', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_WalkRouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_WalkRouteResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DistanceSearch_DistanceQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DistanceSearch_DistanceQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_SearchCity(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_SearchCity', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DistanceSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DistanceSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_WalkPath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_WalkPath', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteBusLineItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteBusLineItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_RouteSearch_DrivePlanQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_RouteSearch_DrivePlanQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DrivePlanStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DrivePlanStep', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_TimeInfo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_TimeInfo', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DriveStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DriveStep', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_TruckStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_TruckStep', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DriveRouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DriveRouteResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DrivePath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DrivePath', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_TruckPath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_TruckPath', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_Doorway(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_Doorway', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DrivePlanPath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DrivePlanPath', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_TimeInfosElement(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_TimeInfosElement', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_DistanceItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_DistanceItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_route_Path(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_route_Path', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_road_Road(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_road_Road', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_road_Crossroad(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_road_Crossroad', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_nearby_NearbyInfo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_nearby_NearbyInfo', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_nearby_UploadInfo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_nearby_UploadInfo', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_nearby_NearbySearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_nearby_NearbySearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_nearby_NearbySearchResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_nearby_NearbySearchResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_nearby_NearbySearch_NearbyQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_nearby_NearbySearch_NearbyQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_a_(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_a_', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_routepoisearch_RoutePOIItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_routepoisearch_RoutePOIItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_routepoisearch_RoutePOISearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_routepoisearch_RoutePOISearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_routepoisearch_RoutePOISearchResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_routepoisearch_RoutePOISearchResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_routepoisearch_RoutePOISearchQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_routepoisearch_RoutePOISearchQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_cloud_CloudItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_cloud_CloudItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_cloud_CloudSearch_Query(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_cloud_CloudSearch_Query', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_cloud_CloudResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_cloud_CloudResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_cloud_CloudSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_cloud_CloudSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_cloud_CloudSearch_SearchBound(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_cloud_CloudSearch_SearchBound', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_cloud_CloudImage(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_cloud_CloudImage', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_cloud_CloudSearch_Sortingrules(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_cloud_CloudSearch_Sortingrules', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_cloud_CloudItemDetail(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_cloud_CloudItemDetail', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_weather_LocalDayWeatherForecast(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_weather_LocalDayWeatherForecast', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_weather_WeatherSearchQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_weather_WeatherSearchQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_weather_LocalWeatherForecastResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_weather_LocalWeatherForecastResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_weather_LocalWeatherForecast(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_weather_LocalWeatherForecast', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_weather_WeatherSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_weather_WeatherSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_weather_LocalWeatherLive(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_weather_LocalWeatherLive', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_weather_LocalWeatherLiveResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_weather_LocalWeatherLiveResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_BusinessArea(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_BusinessArea', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_GeocodeQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_GeocodeQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_GeocodeSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_GeocodeSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_RegeocodeResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_RegeocodeResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_GeocodeResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_GeocodeResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_AoiItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_AoiItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_RegeocodeRoad(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_RegeocodeRoad', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_GeocodeAddress(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_GeocodeAddress', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_RegeocodeQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_RegeocodeQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_StreetNumber(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_StreetNumber', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_geocoder_RegeocodeAddress(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_geocoder_RegeocodeAddress', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_district_DistrictSearchQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_district_DistrictSearchQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_district_DistrictSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_district_DistrictSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_district_DistrictResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_district_DistrictResult', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_district_DistrictItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_district_DistrictItem', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_help_Tip(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_help_Tip', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_help_InputtipsQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_help_InputtipsQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_help_Inputtips(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_help_Inputtips', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_share_ShareSearch_ShareNaviQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_share_ShareSearch_ShareNaviQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_share_ShareSearch_ShareBusRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_share_ShareSearch_ShareBusRouteQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_share_ShareSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_share_ShareSearch', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_share_ShareSearch_ShareFromAndTo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_share_ShareSearch_ShareFromAndTo', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_share_ShareSearch_ShareWalkRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_share_ShareSearch_ShareWalkRouteQuery', {'refId': ref.refId});
  return result;
}

Future<bool> isKindOfcom_amap_api_services_share_ShareSearch_ShareDrivingRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfcom_amap_api_services_share_ShareSearch_ShareDrivingRouteQuery', {'refId': ref.refId});
  return result;
}


Future<com_amap_api_services_traffic_TrafficStatusInfo> ascom_amap_api_services_traffic_TrafficStatusInfo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_traffic_TrafficStatusInfo', {'refId': ref.refId});
  return com_amap_api_services_traffic_TrafficStatusInfo()..refId = result;
}

Future<com_amap_api_services_traffic_TrafficStatusResult> ascom_amap_api_services_traffic_TrafficStatusResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_traffic_TrafficStatusResult', {'refId': ref.refId});
  return com_amap_api_services_traffic_TrafficStatusResult()..refId = result;
}

Future<com_amap_api_services_traffic_TrafficSearch> ascom_amap_api_services_traffic_TrafficSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_traffic_TrafficSearch', {'refId': ref.refId});
  return com_amap_api_services_traffic_TrafficSearch()..refId = result;
}

Future<com_amap_api_services_traffic_TrafficStatusEvaluation> ascom_amap_api_services_traffic_TrafficStatusEvaluation(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_traffic_TrafficStatusEvaluation', {'refId': ref.refId});
  return com_amap_api_services_traffic_TrafficStatusEvaluation()..refId = result;
}

Future<com_amap_api_services_busline_BusLineItem> ascom_amap_api_services_busline_BusLineItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_busline_BusLineItem', {'refId': ref.refId});
  return com_amap_api_services_busline_BusLineItem()..refId = result;
}

Future<com_amap_api_services_busline_BusStationResult> ascom_amap_api_services_busline_BusStationResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_busline_BusStationResult', {'refId': ref.refId});
  return com_amap_api_services_busline_BusStationResult()..refId = result;
}

Future<com_amap_api_services_busline_BusStationSearch> ascom_amap_api_services_busline_BusStationSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_busline_BusStationSearch', {'refId': ref.refId});
  return com_amap_api_services_busline_BusStationSearch()..refId = result;
}

Future<com_amap_api_services_busline_BusLineSearch> ascom_amap_api_services_busline_BusLineSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_busline_BusLineSearch', {'refId': ref.refId});
  return com_amap_api_services_busline_BusLineSearch()..refId = result;
}

Future<com_amap_api_services_busline_BusLineQuery> ascom_amap_api_services_busline_BusLineQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_busline_BusLineQuery', {'refId': ref.refId});
  return com_amap_api_services_busline_BusLineQuery()..refId = result;
}

Future<com_amap_api_services_busline_BusLineResult> ascom_amap_api_services_busline_BusLineResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_busline_BusLineResult', {'refId': ref.refId});
  return com_amap_api_services_busline_BusLineResult()..refId = result;
}

Future<com_amap_api_services_busline_BusStationItem> ascom_amap_api_services_busline_BusStationItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_busline_BusStationItem', {'refId': ref.refId});
  return com_amap_api_services_busline_BusStationItem()..refId = result;
}

Future<com_amap_api_services_busline_BusStationQuery> ascom_amap_api_services_busline_BusStationQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_busline_BusStationQuery', {'refId': ref.refId});
  return com_amap_api_services_busline_BusStationQuery()..refId = result;
}

Future<com_amap_api_services_core_AMapException> ascom_amap_api_services_core_AMapException(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_core_AMapException', {'refId': ref.refId});
  return com_amap_api_services_core_AMapException()..refId = result;
}

Future<com_amap_api_services_core_ServiceSettings> ascom_amap_api_services_core_ServiceSettings(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_core_ServiceSettings', {'refId': ref.refId});
  return com_amap_api_services_core_ServiceSettings()..refId = result;
}

Future<com_amap_api_services_core_SearchUtils> ascom_amap_api_services_core_SearchUtils(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_core_SearchUtils', {'refId': ref.refId});
  return com_amap_api_services_core_SearchUtils()..refId = result;
}

Future<com_amap_api_services_core_LatLonSharePoint> ascom_amap_api_services_core_LatLonSharePoint(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_core_LatLonSharePoint', {'refId': ref.refId});
  return com_amap_api_services_core_LatLonSharePoint()..refId = result;
}

Future<com_amap_api_services_core_LatLonPoint> ascom_amap_api_services_core_LatLonPoint(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_core_LatLonPoint', {'refId': ref.refId});
  return com_amap_api_services_core_LatLonPoint()..refId = result;
}

Future<com_amap_api_services_core_PoiItem> ascom_amap_api_services_core_PoiItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_core_PoiItem', {'refId': ref.refId});
  return com_amap_api_services_core_PoiItem()..refId = result;
}

Future<com_amap_api_services_core_SuggestionCity> ascom_amap_api_services_core_SuggestionCity(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_core_SuggestionCity', {'refId': ref.refId});
  return com_amap_api_services_core_SuggestionCity()..refId = result;
}

Future<com_amap_api_services_poisearch_Photo> ascom_amap_api_services_poisearch_Photo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_poisearch_Photo', {'refId': ref.refId});
  return com_amap_api_services_poisearch_Photo()..refId = result;
}

Future<com_amap_api_services_poisearch_SubPoiItem> ascom_amap_api_services_poisearch_SubPoiItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_poisearch_SubPoiItem', {'refId': ref.refId});
  return com_amap_api_services_poisearch_SubPoiItem()..refId = result;
}

Future<com_amap_api_services_poisearch_PoiItemExtension> ascom_amap_api_services_poisearch_PoiItemExtension(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_poisearch_PoiItemExtension', {'refId': ref.refId});
  return com_amap_api_services_poisearch_PoiItemExtension()..refId = result;
}

Future<com_amap_api_services_poisearch_PoiSearch_SearchBound> ascom_amap_api_services_poisearch_PoiSearch_SearchBound(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_poisearch_PoiSearch_SearchBound', {'refId': ref.refId});
  return com_amap_api_services_poisearch_PoiSearch_SearchBound()..refId = result;
}

Future<com_amap_api_services_poisearch_PoiResult> ascom_amap_api_services_poisearch_PoiResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_poisearch_PoiResult', {'refId': ref.refId});
  return com_amap_api_services_poisearch_PoiResult()..refId = result;
}

Future<com_amap_api_services_poisearch_PoiSearch> ascom_amap_api_services_poisearch_PoiSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_poisearch_PoiSearch', {'refId': ref.refId});
  return com_amap_api_services_poisearch_PoiSearch()..refId = result;
}

Future<com_amap_api_services_poisearch_PoiSearch_Query> ascom_amap_api_services_poisearch_PoiSearch_Query(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_poisearch_PoiSearch_Query', {'refId': ref.refId});
  return com_amap_api_services_poisearch_PoiSearch_Query()..refId = result;
}

Future<com_amap_api_services_poisearch_IndoorData> ascom_amap_api_services_poisearch_IndoorData(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_poisearch_IndoorData', {'refId': ref.refId});
  return com_amap_api_services_poisearch_IndoorData()..refId = result;
}

Future<com_amap_api_services_route_Railway> ascom_amap_api_services_route_Railway(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_Railway', {'refId': ref.refId});
  return com_amap_api_services_route_Railway()..refId = result;
}

Future<com_amap_api_services_route_BusPath> ascom_amap_api_services_route_BusPath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_BusPath', {'refId': ref.refId});
  return com_amap_api_services_route_BusPath()..refId = result;
}

Future<com_amap_api_services_route_DriveRoutePlanResult> ascom_amap_api_services_route_DriveRoutePlanResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DriveRoutePlanResult', {'refId': ref.refId});
  return com_amap_api_services_route_DriveRoutePlanResult()..refId = result;
}

Future<com_amap_api_services_route_RouteSearch_TruckRouteQuery> ascom_amap_api_services_route_RouteSearch_TruckRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteSearch_TruckRouteQuery', {'refId': ref.refId});
  return com_amap_api_services_route_RouteSearch_TruckRouteQuery()..refId = result;
}

Future<com_amap_api_services_route_TMC> ascom_amap_api_services_route_TMC(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_TMC', {'refId': ref.refId});
  return com_amap_api_services_route_TMC()..refId = result;
}

Future<com_amap_api_services_route_RouteBusWalkItem> ascom_amap_api_services_route_RouteBusWalkItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteBusWalkItem', {'refId': ref.refId});
  return com_amap_api_services_route_RouteBusWalkItem()..refId = result;
}

Future<com_amap_api_services_route_RouteResult> ascom_amap_api_services_route_RouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteResult', {'refId': ref.refId});
  return com_amap_api_services_route_RouteResult()..refId = result;
}

Future<com_amap_api_services_route_RouteSearch> ascom_amap_api_services_route_RouteSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteSearch', {'refId': ref.refId});
  return com_amap_api_services_route_RouteSearch()..refId = result;
}

Future<com_amap_api_services_route_BusStep> ascom_amap_api_services_route_BusStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_BusStep', {'refId': ref.refId});
  return com_amap_api_services_route_BusStep()..refId = result;
}

Future<com_amap_api_services_route_TaxiItem> ascom_amap_api_services_route_TaxiItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_TaxiItem', {'refId': ref.refId});
  return com_amap_api_services_route_TaxiItem()..refId = result;
}

Future<com_amap_api_services_route_BusRouteResult> ascom_amap_api_services_route_BusRouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_BusRouteResult', {'refId': ref.refId});
  return com_amap_api_services_route_BusRouteResult()..refId = result;
}

Future<com_amap_api_services_route_RoutePlanResult> ascom_amap_api_services_route_RoutePlanResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RoutePlanResult', {'refId': ref.refId});
  return com_amap_api_services_route_RoutePlanResult()..refId = result;
}

Future<com_amap_api_services_route_RailwaySpace> ascom_amap_api_services_route_RailwaySpace(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RailwaySpace', {'refId': ref.refId});
  return com_amap_api_services_route_RailwaySpace()..refId = result;
}

Future<com_amap_api_services_route_TruckRouteRestult> ascom_amap_api_services_route_TruckRouteRestult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_TruckRouteRestult', {'refId': ref.refId});
  return com_amap_api_services_route_TruckRouteRestult()..refId = result;
}

Future<com_amap_api_services_route_RouteSearch_RideRouteQuery> ascom_amap_api_services_route_RouteSearch_RideRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteSearch_RideRouteQuery', {'refId': ref.refId});
  return com_amap_api_services_route_RouteSearch_RideRouteQuery()..refId = result;
}

Future<com_amap_api_services_route_RouteSearch_DriveRouteQuery> ascom_amap_api_services_route_RouteSearch_DriveRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteSearch_DriveRouteQuery', {'refId': ref.refId});
  return com_amap_api_services_route_RouteSearch_DriveRouteQuery()..refId = result;
}

Future<com_amap_api_services_route_RouteRailwayItem> ascom_amap_api_services_route_RouteRailwayItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteRailwayItem', {'refId': ref.refId});
  return com_amap_api_services_route_RouteRailwayItem()..refId = result;
}

Future<com_amap_api_services_route_WalkStep> ascom_amap_api_services_route_WalkStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_WalkStep', {'refId': ref.refId});
  return com_amap_api_services_route_WalkStep()..refId = result;
}

Future<com_amap_api_services_route_RailwayStationItem> ascom_amap_api_services_route_RailwayStationItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RailwayStationItem', {'refId': ref.refId});
  return com_amap_api_services_route_RailwayStationItem()..refId = result;
}

Future<com_amap_api_services_route_RideRouteResult> ascom_amap_api_services_route_RideRouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RideRouteResult', {'refId': ref.refId});
  return com_amap_api_services_route_RideRouteResult()..refId = result;
}

Future<com_amap_api_services_route_RouteSearch_FromAndTo> ascom_amap_api_services_route_RouteSearch_FromAndTo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteSearch_FromAndTo', {'refId': ref.refId});
  return com_amap_api_services_route_RouteSearch_FromAndTo()..refId = result;
}

Future<com_amap_api_services_route_RidePath> ascom_amap_api_services_route_RidePath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RidePath', {'refId': ref.refId});
  return com_amap_api_services_route_RidePath()..refId = result;
}

Future<com_amap_api_services_route_RouteSearch_BusRouteQuery> ascom_amap_api_services_route_RouteSearch_BusRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteSearch_BusRouteQuery', {'refId': ref.refId});
  return com_amap_api_services_route_RouteSearch_BusRouteQuery()..refId = result;
}

Future<com_amap_api_services_route_RideStep> ascom_amap_api_services_route_RideStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RideStep', {'refId': ref.refId});
  return com_amap_api_services_route_RideStep()..refId = result;
}

Future<com_amap_api_services_route_RouteSearchCity> ascom_amap_api_services_route_RouteSearchCity(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteSearchCity', {'refId': ref.refId});
  return com_amap_api_services_route_RouteSearchCity()..refId = result;
}

Future<com_amap_api_services_route_DistanceResult> ascom_amap_api_services_route_DistanceResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DistanceResult', {'refId': ref.refId});
  return com_amap_api_services_route_DistanceResult()..refId = result;
}

Future<com_amap_api_services_route_RouteSearch_WalkRouteQuery> ascom_amap_api_services_route_RouteSearch_WalkRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteSearch_WalkRouteQuery', {'refId': ref.refId});
  return com_amap_api_services_route_RouteSearch_WalkRouteQuery()..refId = result;
}

Future<com_amap_api_services_route_District> ascom_amap_api_services_route_District(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_District', {'refId': ref.refId});
  return com_amap_api_services_route_District()..refId = result;
}

Future<com_amap_api_services_route_WalkRouteResult> ascom_amap_api_services_route_WalkRouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_WalkRouteResult', {'refId': ref.refId});
  return com_amap_api_services_route_WalkRouteResult()..refId = result;
}

Future<com_amap_api_services_route_DistanceSearch_DistanceQuery> ascom_amap_api_services_route_DistanceSearch_DistanceQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DistanceSearch_DistanceQuery', {'refId': ref.refId});
  return com_amap_api_services_route_DistanceSearch_DistanceQuery()..refId = result;
}

Future<com_amap_api_services_route_SearchCity> ascom_amap_api_services_route_SearchCity(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_SearchCity', {'refId': ref.refId});
  return com_amap_api_services_route_SearchCity()..refId = result;
}

Future<com_amap_api_services_route_DistanceSearch> ascom_amap_api_services_route_DistanceSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DistanceSearch', {'refId': ref.refId});
  return com_amap_api_services_route_DistanceSearch()..refId = result;
}

Future<com_amap_api_services_route_WalkPath> ascom_amap_api_services_route_WalkPath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_WalkPath', {'refId': ref.refId});
  return com_amap_api_services_route_WalkPath()..refId = result;
}

Future<com_amap_api_services_route_RouteBusLineItem> ascom_amap_api_services_route_RouteBusLineItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteBusLineItem', {'refId': ref.refId});
  return com_amap_api_services_route_RouteBusLineItem()..refId = result;
}

Future<com_amap_api_services_route_RouteSearch_DrivePlanQuery> ascom_amap_api_services_route_RouteSearch_DrivePlanQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_RouteSearch_DrivePlanQuery', {'refId': ref.refId});
  return com_amap_api_services_route_RouteSearch_DrivePlanQuery()..refId = result;
}

Future<com_amap_api_services_route_DrivePlanStep> ascom_amap_api_services_route_DrivePlanStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DrivePlanStep', {'refId': ref.refId});
  return com_amap_api_services_route_DrivePlanStep()..refId = result;
}

Future<com_amap_api_services_route_TimeInfo> ascom_amap_api_services_route_TimeInfo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_TimeInfo', {'refId': ref.refId});
  return com_amap_api_services_route_TimeInfo()..refId = result;
}

Future<com_amap_api_services_route_DriveStep> ascom_amap_api_services_route_DriveStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DriveStep', {'refId': ref.refId});
  return com_amap_api_services_route_DriveStep()..refId = result;
}

Future<com_amap_api_services_route_TruckStep> ascom_amap_api_services_route_TruckStep(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_TruckStep', {'refId': ref.refId});
  return com_amap_api_services_route_TruckStep()..refId = result;
}

Future<com_amap_api_services_route_DriveRouteResult> ascom_amap_api_services_route_DriveRouteResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DriveRouteResult', {'refId': ref.refId});
  return com_amap_api_services_route_DriveRouteResult()..refId = result;
}

Future<com_amap_api_services_route_DrivePath> ascom_amap_api_services_route_DrivePath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DrivePath', {'refId': ref.refId});
  return com_amap_api_services_route_DrivePath()..refId = result;
}

Future<com_amap_api_services_route_TruckPath> ascom_amap_api_services_route_TruckPath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_TruckPath', {'refId': ref.refId});
  return com_amap_api_services_route_TruckPath()..refId = result;
}

Future<com_amap_api_services_route_Doorway> ascom_amap_api_services_route_Doorway(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_Doorway', {'refId': ref.refId});
  return com_amap_api_services_route_Doorway()..refId = result;
}

Future<com_amap_api_services_route_DrivePlanPath> ascom_amap_api_services_route_DrivePlanPath(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DrivePlanPath', {'refId': ref.refId});
  return com_amap_api_services_route_DrivePlanPath()..refId = result;
}

Future<com_amap_api_services_route_TimeInfosElement> ascom_amap_api_services_route_TimeInfosElement(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_TimeInfosElement', {'refId': ref.refId});
  return com_amap_api_services_route_TimeInfosElement()..refId = result;
}

Future<com_amap_api_services_route_DistanceItem> ascom_amap_api_services_route_DistanceItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_DistanceItem', {'refId': ref.refId});
  return com_amap_api_services_route_DistanceItem()..refId = result;
}

Future<com_amap_api_services_route_Path> ascom_amap_api_services_route_Path(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_route_Path', {'refId': ref.refId});
  return com_amap_api_services_route_Path()..refId = result;
}

Future<com_amap_api_services_road_Road> ascom_amap_api_services_road_Road(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_road_Road', {'refId': ref.refId});
  return com_amap_api_services_road_Road()..refId = result;
}

Future<com_amap_api_services_road_Crossroad> ascom_amap_api_services_road_Crossroad(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_road_Crossroad', {'refId': ref.refId});
  return com_amap_api_services_road_Crossroad()..refId = result;
}

Future<com_amap_api_services_nearby_NearbyInfo> ascom_amap_api_services_nearby_NearbyInfo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_nearby_NearbyInfo', {'refId': ref.refId});
  return com_amap_api_services_nearby_NearbyInfo()..refId = result;
}

Future<com_amap_api_services_nearby_UploadInfo> ascom_amap_api_services_nearby_UploadInfo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_nearby_UploadInfo', {'refId': ref.refId});
  return com_amap_api_services_nearby_UploadInfo()..refId = result;
}

Future<com_amap_api_services_nearby_NearbySearch> ascom_amap_api_services_nearby_NearbySearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_nearby_NearbySearch', {'refId': ref.refId});
  return com_amap_api_services_nearby_NearbySearch()..refId = result;
}

Future<com_amap_api_services_nearby_NearbySearchResult> ascom_amap_api_services_nearby_NearbySearchResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_nearby_NearbySearchResult', {'refId': ref.refId});
  return com_amap_api_services_nearby_NearbySearchResult()..refId = result;
}

Future<com_amap_api_services_nearby_NearbySearch_NearbyQuery> ascom_amap_api_services_nearby_NearbySearch_NearbyQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_nearby_NearbySearch_NearbyQuery', {'refId': ref.refId});
  return com_amap_api_services_nearby_NearbySearch_NearbyQuery()..refId = result;
}

Future<com_amap_api_services_a_> ascom_amap_api_services_a_(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_a_', {'refId': ref.refId});
  return com_amap_api_services_a_()..refId = result;
}

Future<com_amap_api_services_routepoisearch_RoutePOIItem> ascom_amap_api_services_routepoisearch_RoutePOIItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_routepoisearch_RoutePOIItem', {'refId': ref.refId});
  return com_amap_api_services_routepoisearch_RoutePOIItem()..refId = result;
}

Future<com_amap_api_services_routepoisearch_RoutePOISearch> ascom_amap_api_services_routepoisearch_RoutePOISearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_routepoisearch_RoutePOISearch', {'refId': ref.refId});
  return com_amap_api_services_routepoisearch_RoutePOISearch()..refId = result;
}

Future<com_amap_api_services_routepoisearch_RoutePOISearchResult> ascom_amap_api_services_routepoisearch_RoutePOISearchResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_routepoisearch_RoutePOISearchResult', {'refId': ref.refId});
  return com_amap_api_services_routepoisearch_RoutePOISearchResult()..refId = result;
}

Future<com_amap_api_services_routepoisearch_RoutePOISearchQuery> ascom_amap_api_services_routepoisearch_RoutePOISearchQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_routepoisearch_RoutePOISearchQuery', {'refId': ref.refId});
  return com_amap_api_services_routepoisearch_RoutePOISearchQuery()..refId = result;
}

Future<com_amap_api_services_cloud_CloudItem> ascom_amap_api_services_cloud_CloudItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_cloud_CloudItem', {'refId': ref.refId});
  return com_amap_api_services_cloud_CloudItem()..refId = result;
}

Future<com_amap_api_services_cloud_CloudSearch_Query> ascom_amap_api_services_cloud_CloudSearch_Query(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_cloud_CloudSearch_Query', {'refId': ref.refId});
  return com_amap_api_services_cloud_CloudSearch_Query()..refId = result;
}

Future<com_amap_api_services_cloud_CloudResult> ascom_amap_api_services_cloud_CloudResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_cloud_CloudResult', {'refId': ref.refId});
  return com_amap_api_services_cloud_CloudResult()..refId = result;
}

Future<com_amap_api_services_cloud_CloudSearch> ascom_amap_api_services_cloud_CloudSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_cloud_CloudSearch', {'refId': ref.refId});
  return com_amap_api_services_cloud_CloudSearch()..refId = result;
}

Future<com_amap_api_services_cloud_CloudSearch_SearchBound> ascom_amap_api_services_cloud_CloudSearch_SearchBound(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_cloud_CloudSearch_SearchBound', {'refId': ref.refId});
  return com_amap_api_services_cloud_CloudSearch_SearchBound()..refId = result;
}

Future<com_amap_api_services_cloud_CloudImage> ascom_amap_api_services_cloud_CloudImage(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_cloud_CloudImage', {'refId': ref.refId});
  return com_amap_api_services_cloud_CloudImage()..refId = result;
}

Future<com_amap_api_services_cloud_CloudSearch_Sortingrules> ascom_amap_api_services_cloud_CloudSearch_Sortingrules(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_cloud_CloudSearch_Sortingrules', {'refId': ref.refId});
  return com_amap_api_services_cloud_CloudSearch_Sortingrules()..refId = result;
}

Future<com_amap_api_services_cloud_CloudItemDetail> ascom_amap_api_services_cloud_CloudItemDetail(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_cloud_CloudItemDetail', {'refId': ref.refId});
  return com_amap_api_services_cloud_CloudItemDetail()..refId = result;
}

Future<com_amap_api_services_weather_LocalDayWeatherForecast> ascom_amap_api_services_weather_LocalDayWeatherForecast(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_weather_LocalDayWeatherForecast', {'refId': ref.refId});
  return com_amap_api_services_weather_LocalDayWeatherForecast()..refId = result;
}

Future<com_amap_api_services_weather_WeatherSearchQuery> ascom_amap_api_services_weather_WeatherSearchQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_weather_WeatherSearchQuery', {'refId': ref.refId});
  return com_amap_api_services_weather_WeatherSearchQuery()..refId = result;
}

Future<com_amap_api_services_weather_LocalWeatherForecastResult> ascom_amap_api_services_weather_LocalWeatherForecastResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_weather_LocalWeatherForecastResult', {'refId': ref.refId});
  return com_amap_api_services_weather_LocalWeatherForecastResult()..refId = result;
}

Future<com_amap_api_services_weather_LocalWeatherForecast> ascom_amap_api_services_weather_LocalWeatherForecast(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_weather_LocalWeatherForecast', {'refId': ref.refId});
  return com_amap_api_services_weather_LocalWeatherForecast()..refId = result;
}

Future<com_amap_api_services_weather_WeatherSearch> ascom_amap_api_services_weather_WeatherSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_weather_WeatherSearch', {'refId': ref.refId});
  return com_amap_api_services_weather_WeatherSearch()..refId = result;
}

Future<com_amap_api_services_weather_LocalWeatherLive> ascom_amap_api_services_weather_LocalWeatherLive(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_weather_LocalWeatherLive', {'refId': ref.refId});
  return com_amap_api_services_weather_LocalWeatherLive()..refId = result;
}

Future<com_amap_api_services_weather_LocalWeatherLiveResult> ascom_amap_api_services_weather_LocalWeatherLiveResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_weather_LocalWeatherLiveResult', {'refId': ref.refId});
  return com_amap_api_services_weather_LocalWeatherLiveResult()..refId = result;
}

Future<com_amap_api_services_geocoder_BusinessArea> ascom_amap_api_services_geocoder_BusinessArea(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_BusinessArea', {'refId': ref.refId});
  return com_amap_api_services_geocoder_BusinessArea()..refId = result;
}

Future<com_amap_api_services_geocoder_GeocodeQuery> ascom_amap_api_services_geocoder_GeocodeQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_GeocodeQuery', {'refId': ref.refId});
  return com_amap_api_services_geocoder_GeocodeQuery()..refId = result;
}

Future<com_amap_api_services_geocoder_GeocodeSearch> ascom_amap_api_services_geocoder_GeocodeSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_GeocodeSearch', {'refId': ref.refId});
  return com_amap_api_services_geocoder_GeocodeSearch()..refId = result;
}

Future<com_amap_api_services_geocoder_RegeocodeResult> ascom_amap_api_services_geocoder_RegeocodeResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_RegeocodeResult', {'refId': ref.refId});
  return com_amap_api_services_geocoder_RegeocodeResult()..refId = result;
}

Future<com_amap_api_services_geocoder_GeocodeResult> ascom_amap_api_services_geocoder_GeocodeResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_GeocodeResult', {'refId': ref.refId});
  return com_amap_api_services_geocoder_GeocodeResult()..refId = result;
}

Future<com_amap_api_services_geocoder_AoiItem> ascom_amap_api_services_geocoder_AoiItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_AoiItem', {'refId': ref.refId});
  return com_amap_api_services_geocoder_AoiItem()..refId = result;
}

Future<com_amap_api_services_geocoder_RegeocodeRoad> ascom_amap_api_services_geocoder_RegeocodeRoad(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_RegeocodeRoad', {'refId': ref.refId});
  return com_amap_api_services_geocoder_RegeocodeRoad()..refId = result;
}

Future<com_amap_api_services_geocoder_GeocodeAddress> ascom_amap_api_services_geocoder_GeocodeAddress(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_GeocodeAddress', {'refId': ref.refId});
  return com_amap_api_services_geocoder_GeocodeAddress()..refId = result;
}

Future<com_amap_api_services_geocoder_RegeocodeQuery> ascom_amap_api_services_geocoder_RegeocodeQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_RegeocodeQuery', {'refId': ref.refId});
  return com_amap_api_services_geocoder_RegeocodeQuery()..refId = result;
}

Future<com_amap_api_services_geocoder_StreetNumber> ascom_amap_api_services_geocoder_StreetNumber(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_StreetNumber', {'refId': ref.refId});
  return com_amap_api_services_geocoder_StreetNumber()..refId = result;
}

Future<com_amap_api_services_geocoder_RegeocodeAddress> ascom_amap_api_services_geocoder_RegeocodeAddress(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_geocoder_RegeocodeAddress', {'refId': ref.refId});
  return com_amap_api_services_geocoder_RegeocodeAddress()..refId = result;
}

Future<com_amap_api_services_district_DistrictSearchQuery> ascom_amap_api_services_district_DistrictSearchQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_district_DistrictSearchQuery', {'refId': ref.refId});
  return com_amap_api_services_district_DistrictSearchQuery()..refId = result;
}

Future<com_amap_api_services_district_DistrictSearch> ascom_amap_api_services_district_DistrictSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_district_DistrictSearch', {'refId': ref.refId});
  return com_amap_api_services_district_DistrictSearch()..refId = result;
}

Future<com_amap_api_services_district_DistrictResult> ascom_amap_api_services_district_DistrictResult(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_district_DistrictResult', {'refId': ref.refId});
  return com_amap_api_services_district_DistrictResult()..refId = result;
}

Future<com_amap_api_services_district_DistrictItem> ascom_amap_api_services_district_DistrictItem(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_district_DistrictItem', {'refId': ref.refId});
  return com_amap_api_services_district_DistrictItem()..refId = result;
}

Future<com_amap_api_services_help_Tip> ascom_amap_api_services_help_Tip(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_help_Tip', {'refId': ref.refId});
  return com_amap_api_services_help_Tip()..refId = result;
}

Future<com_amap_api_services_help_InputtipsQuery> ascom_amap_api_services_help_InputtipsQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_help_InputtipsQuery', {'refId': ref.refId});
  return com_amap_api_services_help_InputtipsQuery()..refId = result;
}

Future<com_amap_api_services_help_Inputtips> ascom_amap_api_services_help_Inputtips(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_help_Inputtips', {'refId': ref.refId});
  return com_amap_api_services_help_Inputtips()..refId = result;
}

Future<com_amap_api_services_share_ShareSearch_ShareNaviQuery> ascom_amap_api_services_share_ShareSearch_ShareNaviQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_share_ShareSearch_ShareNaviQuery', {'refId': ref.refId});
  return com_amap_api_services_share_ShareSearch_ShareNaviQuery()..refId = result;
}

Future<com_amap_api_services_share_ShareSearch_ShareBusRouteQuery> ascom_amap_api_services_share_ShareSearch_ShareBusRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_share_ShareSearch_ShareBusRouteQuery', {'refId': ref.refId});
  return com_amap_api_services_share_ShareSearch_ShareBusRouteQuery()..refId = result;
}

Future<com_amap_api_services_share_ShareSearch> ascom_amap_api_services_share_ShareSearch(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_share_ShareSearch', {'refId': ref.refId});
  return com_amap_api_services_share_ShareSearch()..refId = result;
}

Future<com_amap_api_services_share_ShareSearch_ShareFromAndTo> ascom_amap_api_services_share_ShareSearch_ShareFromAndTo(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_share_ShareSearch_ShareFromAndTo', {'refId': ref.refId});
  return com_amap_api_services_share_ShareSearch_ShareFromAndTo()..refId = result;
}

Future<com_amap_api_services_share_ShareSearch_ShareWalkRouteQuery> ascom_amap_api_services_share_ShareSearch_ShareWalkRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_share_ShareSearch_ShareWalkRouteQuery', {'refId': ref.refId});
  return com_amap_api_services_share_ShareSearch_ShareWalkRouteQuery()..refId = result;
}

Future<com_amap_api_services_share_ShareSearch_ShareDrivingRouteQuery> ascom_amap_api_services_share_ShareSearch_ShareDrivingRouteQuery(Ref ref) async {
  final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::ascom_amap_api_services_share_ShareSearch_ShareDrivingRouteQuery', {'refId': ref.refId});
  return com_amap_api_services_share_ShareSearch_ShareDrivingRouteQuery()..refId = result;
}
