// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:amap_search_fluttify/src/ios/ios.export.g.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
extension TypeOpAmapSearchFluttifyIOS on Object {
  // type check
  Future<bool> is__<T>() async {
    final typeName = T.toString();
    if (RegExp('(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)').hasMatch(typeName)) {
      return this is T;
    }
    else if (T == AMapPOISearchBaseRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPOISearchBaseRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapPOIIDSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPOIIDSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapPOIKeywordsSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPOIKeywordsSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapPOIAroundSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPOIAroundSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapPOIPolygonSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPOIPolygonSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapPOISearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPOISearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoutePOISearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoutePOISearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoutePOISearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoutePOISearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapInputTipsSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapInputTipsSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapInputTipsSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapInputTipsSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapGeocodeSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapGeocodeSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapGeocodeSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapGeocodeSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapReGeocodeSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapReGeocodeSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapReGeocodeSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapReGeocodeSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapBusStopSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapBusStopSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapBusStopSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapBusStopSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapBusLineBaseSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapBusLineBaseSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapBusLineNameSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapBusLineNameSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapBusLineIDSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapBusLineIDSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapBusLineSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapBusLineSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapDistrictSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapDistrictSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapDistrictSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapDistrictSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRouteSearchBaseRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRouteSearchBaseRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapDrivingRouteSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapDrivingRouteSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapWalkingRouteSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapWalkingRouteSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapTransitRouteSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapTransitRouteSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRidingRouteSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRidingRouteSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRouteSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRouteSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRidingRouteSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRidingRouteSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapTruckRouteSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapTruckRouteSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapDistanceSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapDistanceSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapDistanceSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapDistanceSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapWeatherSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapWeatherSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapWeatherSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapWeatherSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoadTrafficSearchBaseRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoadTrafficSearchBaseRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoadTrafficSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoadTrafficSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoadTrafficCircleSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoadTrafficCircleSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoadTrafficSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoadTrafficSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapNearbySearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapNearbySearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapNearbySearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapNearbySearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapCloudSearchBaseRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapCloudSearchBaseRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapCloudPOIAroundSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapCloudPOIAroundSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapCloudPOIPolygonSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapCloudPOIPolygonSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapCloudPOIIDSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapCloudPOIIDSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapCloudPOILocalSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapCloudPOILocalSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapCloudPOISearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapCloudPOISearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapShareSearchBaseRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapShareSearchBaseRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapLocationShareSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapLocationShareSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapPOIShareSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPOIShareSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRouteShareSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRouteShareSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapNavigationShareSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapNavigationShareSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapShareSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapShareSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapFutureRouteSearchRequest) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapFutureRouteSearchRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapFutureRouteSearchResponse) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapFutureRouteSearchResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapSearchObject) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapSearchObject', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapGeoPoint) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapGeoPoint', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapGeoPolygon) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapGeoPolygon', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapCity) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapCity', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapSuggestion) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapSuggestion', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapTip) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapTip', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapImage) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapImage', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapPOIExtension) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPOIExtension', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapIndoorData) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapIndoorData', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapSubPOI) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapSubPOI', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoutePOI) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoutePOI', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapPOI) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPOI', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapAOI) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapAOI', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoad) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoad', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoadInter) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoadInter', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapStreetNumber) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapStreetNumber', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapBusinessArea) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapBusinessArea', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapAddressComponent) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapAddressComponent', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapReGeocode) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapReGeocode', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapGeocode) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapGeocode', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapBusStop) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapBusStop', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapBusLine) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapBusLine', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapDistrict) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapDistrict', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapTMC) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapTMC', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapStep) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapStep', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapPath) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapPath', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapFutureTimeInfoElement) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapFutureTimeInfoElement', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapFutureTimeInfo) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapFutureTimeInfo', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapWalking) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapWalking', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapTaxi) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapTaxi', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRailwayStation) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRailwayStation', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRailwaySpace) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRailwaySpace', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRailway) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRailway', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapSegment) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapSegment', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapTransit) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapTransit', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapRoute) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapRoute', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapDistanceResult) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapDistanceResult', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapLocalWeatherLive) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapLocalWeatherLive', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapLocalDayWeatherForecast) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapLocalDayWeatherForecast', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapLocalWeatherForecast) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapLocalWeatherForecast', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapNearbyUserInfo) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapNearbyUserInfo', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapTrafficEvaluation) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapTrafficEvaluation', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapTrafficRoad) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapTrafficRoad', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapTrafficInfo) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapTrafficInfo', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapCloudImage) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapCloudImage', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapCloudPOI) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapCloudPOI', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapNearbyUploadInfo) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapNearbyUploadInfo', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapNearbySearchManager) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapNearbySearchManager', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == AMapSearchAPI) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfAMapSearchAPI', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == CLLocation) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfCLLocation', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == CLHeading) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfCLHeading', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == CGRect) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfCGRect', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == CGPoint) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfCGPoint', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == CGSize) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfCGSize', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == UIEdgeInsets) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfUIEdgeInsets', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == CLLocationCoordinate2D) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfCLLocationCoordinate2D', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == CLLocationManager) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfCLLocationManager', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == NSError) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfNSError', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == NSCoding) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfNSCoding', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == NSCopying) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfNSCopying', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == UIView) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfUIView', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == UIViewController) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfUIViewController', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == UIControl) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfUIControl', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == UIImage) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfUIImage', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == UIColor) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfUIColor', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == NSData) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfNSData', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == NSOperation) {
      final result = await MethodChannel('me.yohom/amap_search_fluttify').invokeMethod('RefClass::isKindOfNSOperation', {'refId': (this as Ref).refId});
      return result;
    }
  }

  // type cast
  T as__<T>() {
    final typeName = T.toString();
    // jsonable 直接造型 返回
    if (RegExp('(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)').hasMatch(typeName)) {
      return this as T;
    }
    // 如果是Ref类的cast, 那么取其refId, 如果本身是refId, 那么直接使用(int)
    else if (T == AMapPOISearchBaseRequest) {
      return (AMapPOISearchBaseRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapPOIIDSearchRequest) {
      return (AMapPOIIDSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapPOIKeywordsSearchRequest) {
      return (AMapPOIKeywordsSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapPOIAroundSearchRequest) {
      return (AMapPOIAroundSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapPOIPolygonSearchRequest) {
      return (AMapPOIPolygonSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapPOISearchResponse) {
      return (AMapPOISearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoutePOISearchRequest) {
      return (AMapRoutePOISearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoutePOISearchResponse) {
      return (AMapRoutePOISearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapInputTipsSearchRequest) {
      return (AMapInputTipsSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapInputTipsSearchResponse) {
      return (AMapInputTipsSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapGeocodeSearchRequest) {
      return (AMapGeocodeSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapGeocodeSearchResponse) {
      return (AMapGeocodeSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapReGeocodeSearchRequest) {
      return (AMapReGeocodeSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapReGeocodeSearchResponse) {
      return (AMapReGeocodeSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapBusStopSearchRequest) {
      return (AMapBusStopSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapBusStopSearchResponse) {
      return (AMapBusStopSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapBusLineBaseSearchRequest) {
      return (AMapBusLineBaseSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapBusLineNameSearchRequest) {
      return (AMapBusLineNameSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapBusLineIDSearchRequest) {
      return (AMapBusLineIDSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapBusLineSearchResponse) {
      return (AMapBusLineSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapDistrictSearchRequest) {
      return (AMapDistrictSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapDistrictSearchResponse) {
      return (AMapDistrictSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRouteSearchBaseRequest) {
      return (AMapRouteSearchBaseRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapDrivingRouteSearchRequest) {
      return (AMapDrivingRouteSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapWalkingRouteSearchRequest) {
      return (AMapWalkingRouteSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapTransitRouteSearchRequest) {
      return (AMapTransitRouteSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRidingRouteSearchRequest) {
      return (AMapRidingRouteSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRouteSearchResponse) {
      return (AMapRouteSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRidingRouteSearchResponse) {
      return (AMapRidingRouteSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapTruckRouteSearchRequest) {
      return (AMapTruckRouteSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapDistanceSearchRequest) {
      return (AMapDistanceSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapDistanceSearchResponse) {
      return (AMapDistanceSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapWeatherSearchRequest) {
      return (AMapWeatherSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapWeatherSearchResponse) {
      return (AMapWeatherSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoadTrafficSearchBaseRequest) {
      return (AMapRoadTrafficSearchBaseRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoadTrafficSearchRequest) {
      return (AMapRoadTrafficSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoadTrafficCircleSearchRequest) {
      return (AMapRoadTrafficCircleSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoadTrafficSearchResponse) {
      return (AMapRoadTrafficSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapNearbySearchRequest) {
      return (AMapNearbySearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapNearbySearchResponse) {
      return (AMapNearbySearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapCloudSearchBaseRequest) {
      return (AMapCloudSearchBaseRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapCloudPOIAroundSearchRequest) {
      return (AMapCloudPOIAroundSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapCloudPOIPolygonSearchRequest) {
      return (AMapCloudPOIPolygonSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapCloudPOIIDSearchRequest) {
      return (AMapCloudPOIIDSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapCloudPOILocalSearchRequest) {
      return (AMapCloudPOILocalSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapCloudPOISearchResponse) {
      return (AMapCloudPOISearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapShareSearchBaseRequest) {
      return (AMapShareSearchBaseRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapLocationShareSearchRequest) {
      return (AMapLocationShareSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapPOIShareSearchRequest) {
      return (AMapPOIShareSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRouteShareSearchRequest) {
      return (AMapRouteShareSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapNavigationShareSearchRequest) {
      return (AMapNavigationShareSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapShareSearchResponse) {
      return (AMapShareSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapFutureRouteSearchRequest) {
      return (AMapFutureRouteSearchRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapFutureRouteSearchResponse) {
      return (AMapFutureRouteSearchResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapSearchObject) {
      return (AMapSearchObject()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapGeoPoint) {
      return (AMapGeoPoint()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapGeoPolygon) {
      return (AMapGeoPolygon()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapCity) {
      return (AMapCity()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapSuggestion) {
      return (AMapSuggestion()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapTip) {
      return (AMapTip()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapImage) {
      return (AMapImage()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapPOIExtension) {
      return (AMapPOIExtension()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapIndoorData) {
      return (AMapIndoorData()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapSubPOI) {
      return (AMapSubPOI()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoutePOI) {
      return (AMapRoutePOI()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapPOI) {
      return (AMapPOI()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapAOI) {
      return (AMapAOI()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoad) {
      return (AMapRoad()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoadInter) {
      return (AMapRoadInter()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapStreetNumber) {
      return (AMapStreetNumber()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapBusinessArea) {
      return (AMapBusinessArea()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapAddressComponent) {
      return (AMapAddressComponent()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapReGeocode) {
      return (AMapReGeocode()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapGeocode) {
      return (AMapGeocode()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapBusStop) {
      return (AMapBusStop()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapBusLine) {
      return (AMapBusLine()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapDistrict) {
      return (AMapDistrict()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapTMC) {
      return (AMapTMC()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapStep) {
      return (AMapStep()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapPath) {
      return (AMapPath()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapFutureTimeInfoElement) {
      return (AMapFutureTimeInfoElement()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapFutureTimeInfo) {
      return (AMapFutureTimeInfo()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapWalking) {
      return (AMapWalking()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapTaxi) {
      return (AMapTaxi()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRailwayStation) {
      return (AMapRailwayStation()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRailwaySpace) {
      return (AMapRailwaySpace()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRailway) {
      return (AMapRailway()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapSegment) {
      return (AMapSegment()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapTransit) {
      return (AMapTransit()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapRoute) {
      return (AMapRoute()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapDistanceResult) {
      return (AMapDistanceResult()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapLocalWeatherLive) {
      return (AMapLocalWeatherLive()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapLocalDayWeatherForecast) {
      return (AMapLocalDayWeatherForecast()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapLocalWeatherForecast) {
      return (AMapLocalWeatherForecast()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapNearbyUserInfo) {
      return (AMapNearbyUserInfo()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapTrafficEvaluation) {
      return (AMapTrafficEvaluation()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapTrafficRoad) {
      return (AMapTrafficRoad()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapTrafficInfo) {
      return (AMapTrafficInfo()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapCloudImage) {
      return (AMapCloudImage()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapCloudPOI) {
      return (AMapCloudPOI()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapNearbyUploadInfo) {
      return (AMapNearbyUploadInfo()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapNearbySearchManager) {
      return (AMapNearbySearchManager()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == AMapSearchAPI) {
      return (AMapSearchAPI()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == CLLocation) {
      return (CLLocation()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == CLHeading) {
      return (CLHeading()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == CGRect) {
      return (CGRect()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == CGPoint) {
      return (CGPoint()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == CGSize) {
      return (CGSize()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == UIEdgeInsets) {
      return (UIEdgeInsets()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == CLLocationCoordinate2D) {
      return (CLLocationCoordinate2D()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == CLLocationManager) {
      return (CLLocationManager()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == NSError) {
      return (NSError()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == NSCoding) {
      return (NSCoding.subInstance()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == NSCopying) {
      return (NSCopying.subInstance()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == UIView) {
      return (UIView()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == UIViewController) {
      return (UIViewController()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == UIControl) {
      return (UIControl()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == UIImage) {
      return (UIImage()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == UIColor) {
      return (UIColor()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == NSData) {
      return (NSData()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
    else if (T == NSOperation) {
      return (NSOperation()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'amap_search_fluttify') as T;
    }
  }
}